
import logging
import spotipy
from spotipy.oauth2 import SpotifyOAuth
from typing import List, Optional
from .models import Playlist, Track
from .library import library
from .config import config

logger = logging.getLogger("mixtape_curator.spotify")

class SpotifyExporter:
    """
    Handles export of generated playlists to Spotify.
    """
    def __init__(self):
        self.sp: Optional[spotipy.Spotify] = None
        
    def _authenticate(self) -> bool:
        """Authenticate with Spotify using OAuth. Returns True if successful."""
        if not config.spotify_client_id or not config.spotify_client_secret:
            logger.warning("Spotify credentials not set in environment.")
            return False
            
        try:
            auth_manager = SpotifyOAuth(
                client_id=config.spotify_client_id,
                client_secret=config.spotify_client_secret,
                redirect_uri=config.spotify_redirect_uri,
                scope="playlist-modify-public playlist-modify-private user-library-read"
            )
            self.sp = spotipy.Spotify(auth_manager=auth_manager)
            user = self.sp.current_user()
            self.user_id = user['id']
            logger.info(f"Authenticated as {user['display_name']} ({self.user_id})")
            return True
        except Exception as e:
            logger.error(f"Spotify authentication failed: {e}")
            return False

    def export_playlist(self, playlist: Playlist, name: str, public: bool = False) -> str:
        """
        Create a Spotify playlist and add tracks.
        Returns the Spotify URL of the created playlist.
        """
        if not self.sp:
            if not self._authenticate():
                return "Spotify Export Failed: Missing credentials or auth error."

        try:
            # 1. Create Playlist
            sp_playlist = self.sp.user_playlist_create(
                user=self.user_id,
                name=name,
                public=public,
                description=f"Generated by Mixtape Curator | Score: {playlist.scores.total:.2f}"
            )
            playlist_id = sp_playlist['id']
            playlist_url = sp_playlist['external_urls']['spotify']
            
            # 2. Resolve Tracks to URIs
            track_uris = []
            tracks = [library.get_track(tid) for tid in playlist.track_ids]
            tracks = [t for t in tracks if t] # filter None
            
            for t in tracks:
                uri = self._resolve_track_uri(t)
                if uri:
                    track_uris.append(uri)
                else:
                    logger.warning(f"Could not find Spotify URI for: {t.title} - {t.artist}")
            
            # 3. Add to Playlist (Batch 100)
            if track_uris:
                for i in range(0, len(track_uris), 100):
                    batch = track_uris[i : i+100]
                    self.sp.playlist_add_items(playlist_id, batch)
                logger.info(f"Added {len(track_uris)} tracks to Spotify playlist.")
                return f"Successfully exported to Spotify: {playlist_url}"
            else:
                return "Created empty playlist (No track matches found)."
                
        except Exception as e:
            logger.error(f"Error creating playlist: {e}")
            return f"Spotify Export Error: {e}"

    def _resolve_track_uri(self, track: Track) -> Optional[str]:
        """Get Spotify URI from track metadata or search."""
        if track.spotify_uri:
            return track.spotify_uri
            
        # Search API
        query = f"artist:{track.artist} track:{track.title}"
        try:
            results = self.sp.search(q=query, type='track', limit=1)
            items = results['tracks']['items']
            if items:
                # Basic validation: ensure artist name match is close?
                # For now trust the top result for 'artist:X track:Y'
                found = items[0]
                return found['uri']
        except Exception as e:
            logger.warning(f"Search failed for {track.title}: {e}")
            
        return None

spotify_exporter = SpotifyExporter()
